"""Events domain."""

from pydotorg.domains.events.controllers import (
    CalendarController,
    EventCategoryController,
    EventController,
    EventLocationController,
    EventOccurrenceController,
    EventsPageController,
)
from pydotorg.domains.events.dependencies import get_events_dependencies
from pydotorg.domains.events.models import Calendar, Event, EventCategory, EventLocation, EventOccurrence
from pydotorg.domains.events.repositories import (
    CalendarRepository,
    EventCategoryRepository,
    EventLocationRepository,
    EventOccurrenceRepository,
    EventRepository,
)
from pydotorg.domains.events.schemas import (
    CalendarCreate,
    CalendarRead,
    CalendarUpdate,
    EventCalendarPageData,
    EventCategoryCreate,
    EventCategoryRead,
    EventCreate,
    EventDetailPageData,
    EventList,
    EventLocationCreate,
    EventLocationRead,
    EventLocationUpdate,
    EventOccurrenceCreate,
    EventOccurrenceRead,
    EventOccurrenceUpdate,
    EventRead,
    EventUpdate,
    EventWithRelations,
)
from pydotorg.domains.events.services import (
    CalendarService,
    EventCategoryService,
    EventLocationService,
    EventOccurrenceService,
    EventService,
)

__all__ = [
    "Calendar",
    "CalendarController",
    "CalendarCreate",
    "CalendarRead",
    "CalendarRepository",
    "CalendarService",
    "CalendarUpdate",
    "Event",
    "EventCalendarPageData",
    "EventCategory",
    "EventCategoryController",
    "EventCategoryCreate",
    "EventCategoryRead",
    "EventCategoryRepository",
    "EventCategoryService",
    "EventController",
    "EventCreate",
    "EventDetailPageData",
    "EventList",
    "EventLocation",
    "EventLocationController",
    "EventLocationCreate",
    "EventLocationRead",
    "EventLocationRepository",
    "EventLocationService",
    "EventLocationUpdate",
    "EventOccurrence",
    "EventOccurrenceController",
    "EventOccurrenceCreate",
    "EventOccurrenceRead",
    "EventOccurrenceRepository",
    "EventOccurrenceService",
    "EventOccurrenceUpdate",
    "EventRead",
    "EventRepository",
    "EventService",
    "EventUpdate",
    "EventWithRelations",
    "EventsPageController",
    "get_events_dependencies",
]
