"""Admin domain URL constants."""

ADMIN = "/admin"
ADMIN_DASHBOARD = f"{ADMIN}/"
ADMIN_USERS = f"{ADMIN}/users"
ADMIN_JOBS = f"{ADMIN}/jobs"
ADMIN_EVENTS = f"{ADMIN}/events"
ADMIN_CONTENT = f"{ADMIN}/content"
ADMIN_PAGES = f"{ADMIN}/pages"
ADMIN_SPONSORS = f"{ADMIN}/sponsors"
ADMIN_BLOGS = f"{ADMIN}/blogs"
ADMIN_SETTINGS = f"{ADMIN}/settings"
ADMIN_LOGS = f"{ADMIN}/logs"
ADMIN_SYSTEM = f"{ADMIN}/system"
ADMIN_EMAIL = f"{ADMIN}/email"
ADMIN_ANALYTICS = f"{ADMIN}/analytics"
