"""add_is_featured_to_jobs

Revision ID: 15ce08df3d24
Revises: e384c31c0ac1
Create Date: 2025-12-13 07:27:04.304929

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "15ce08df3d24"
down_revision: str | None = "e384c31c0ac1"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "banners", "banner_type", existing_type=sa.VARCHAR(length=20), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "banners", "is_dismissible", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    op.alter_column("banners", "is_sitewide", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
    op.alter_column("feeds", "priority", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False)
    op.add_column("jobs", sa.Column("is_featured", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.create_index(op.f("ix_jobs_is_featured"), "jobs", ["is_featured"], unique=False)
    op.alter_column("jobs", "is_featured", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_is_featured"), table_name="jobs")
    op.drop_column("jobs", "is_featured")
    op.alter_column(
        "feeds", "priority", existing_type=sa.INTEGER(), server_default=sa.text("0"), existing_nullable=False
    )
    op.alter_column(
        "banners", "is_sitewide", existing_type=sa.BOOLEAN(), server_default=sa.text("true"), existing_nullable=False
    )
    op.alter_column(
        "banners", "is_dismissible", existing_type=sa.BOOLEAN(), server_default=sa.text("true"), existing_nullable=False
    )
    op.alter_column(
        "banners",
        "banner_type",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'info'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
