"""add_priority_to_feeds

Revision ID: 3cc860d76dbf
Revises: dc83835dede2
Create Date: 2025-12-01 01:41:58.473014

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "3cc860d76dbf"
down_revision: str | None = "dc83835dede2"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blog_entries", "is_featured", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    # Add priority column with server default so existing rows get value 0
    op.add_column("feeds", sa.Column("priority", sa.Integer(), nullable=False, server_default="0"))
    op.create_index(op.f("ix_feeds_priority"), "feeds", ["priority"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feeds_priority"), table_name="feeds")
    op.drop_column("feeds", "priority")
    op.alter_column(
        "blog_entries",
        "is_featured",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
