"""add_sha256_sum_to_release_files

Revision ID: 6a9a0e71a19b
Revises: 15ce08df3d24
Create Date: 2025-12-13 16:28:45.139103

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "6a9a0e71a19b"
down_revision: str | None = "15ce08df3d24"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("release_files", sa.Column("sha256_sum", sa.String(length=200), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release_files", "sha256_sum")
    # ### end Alembic commands ###
