"""add_is_official_to_feeds

Revision ID: afda74ceaa73
Revises: 380becc88f99
Create Date: 2025-12-14 11:15:30.755098

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'afda74ceaa73'
down_revision: str | None = '380becc88f99'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('is_official', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_feeds_is_official'), 'feeds', ['is_official'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeds_is_official'), table_name='feeds')
    op.drop_column('feeds', 'is_official')
    # ### end Alembic commands ###
