"""add_contract_models

Revision ID: c558a6751053
Revises: c6a65f39982f
Create Date: 2025-12-13 16:48:21.378062

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import advanced_alchemy
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "c558a6751053"
down_revision: str | None = "c6a65f39982f"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsor_legal_clauses",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("clause_text", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsor_legal_clauses")),
    )
    op.create_index(op.f("ix_sponsor_legal_clauses_order"), "sponsor_legal_clauses", ["order"], unique=False)
    op.create_index(op.f("ix_sponsor_legal_clauses_slug"), "sponsor_legal_clauses", ["slug"], unique=True)
    op.create_table(
        "sponsor_contracts",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sponsorship_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "outdated", "awaiting_signature", "executed", "nullified", name="contractstatus"),
            nullable=False,
        ),
        sa.Column("revision", sa.SmallInteger(), nullable=False),
        sa.Column("document_pdf", sa.String(length=500), nullable=False),
        sa.Column("document_docx", sa.String(length=500), nullable=False),
        sa.Column("signed_document", sa.String(length=500), nullable=False),
        sa.Column("sponsor_info", sa.Text(), nullable=False),
        sa.Column("sponsor_contact", sa.Text(), nullable=False),
        sa.Column("benefits_list", sa.Text(), nullable=False),
        sa.Column("legal_clauses_text", sa.Text(), nullable=False),
        sa.Column("sent_on", sa.Date(), nullable=True),
        sa.Column("executed_on", sa.Date(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sponsorship_id"],
            ["sponsorships.id"],
            name=op.f("fk_sponsor_contracts_sponsorship_id_sponsorships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsor_contracts")),
        sa.UniqueConstraint("sponsorship_id", name=op.f("uq_sponsor_contracts_sponsorship_id")),
    )
    op.create_index(op.f("ix_sponsor_contracts_status"), "sponsor_contracts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sponsor_contracts_status"), table_name="sponsor_contracts")
    op.drop_table("sponsor_contracts")
    op.drop_index(op.f("ix_sponsor_legal_clauses_slug"), table_name="sponsor_legal_clauses")
    op.drop_index(op.f("ix_sponsor_legal_clauses_order"), table_name="sponsor_legal_clauses")
    op.drop_table("sponsor_legal_clauses")
    # ### end Alembic commands ###
