"""add_recurring_rule_model

Revision ID: c6a65f39982f
Revises: 6a9a0e71a19b
Create Date: 2025-12-13 16:40:49.692796

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import advanced_alchemy
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "c6a65f39982f"
down_revision: str | None = "6a9a0e71a19b"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_recurring_rules",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("event_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("begin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finish", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration", sa.Interval(), nullable=False),
        sa.Column("interval", sa.SmallInteger(), nullable=False),
        sa.Column("frequency", sa.SmallInteger(), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_recurring_rules_event_id_events"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_recurring_rules")),
    )
    op.create_index(op.f("ix_event_recurring_rules_begin"), "event_recurring_rules", ["begin"], unique=False)
    op.create_index(op.f("ix_event_recurring_rules_finish"), "event_recurring_rules", ["finish"], unique=False)
    op.alter_column(
        "release_files",
        "sha256_sum",
        existing_type=sa.VARCHAR(length=200),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "release_files",
        "sha256_sum",
        existing_type=sa.VARCHAR(length=200),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_event_recurring_rules_finish"), table_name="event_recurring_rules")
    op.drop_index(op.f("ix_event_recurring_rules_begin"), table_name="event_recurring_rules")
    op.drop_table("event_recurring_rules")
    # ### end Alembic commands ###
