"""add_api_keys_table

Revision ID: db342d0879cb
Revises: c558a6751053
Create Date: 2025-12-13 18:03:47.126741

"""
from __future__ import annotations

from typing import TYPE_CHECKING

import advanced_alchemy
import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


revision: str = "db342d0879cb"
down_revision: str | None = "c558a6751053"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("api_keys",
    sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column("user_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("key_hash", sa.String(length=64), nullable=False),
    sa.Column("key_prefix", sa.String(length=12), nullable=False),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
    sa.Column("created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column("updated_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys"))
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=False)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
