"""add_is_featured_to_blog_entries

Revision ID: dc83835dede2
Revises: e4ba5c608161
Create Date: 2025-11-30 22:04:31.364095

"""
from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "dc83835dede2"
down_revision: str | None = "e4ba5c608161"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then set default values, then make it non-nullable
    op.add_column("blog_entries", sa.Column("is_featured", sa.Boolean(), nullable=True))
    op.execute("UPDATE blog_entries SET is_featured = false WHERE is_featured IS NULL")
    op.alter_column("blog_entries", "is_featured", nullable=False, server_default=sa.text("false"))
    op.create_index(op.f("ix_blog_entries_is_featured"), "blog_entries", ["is_featured"], unique=False)
    op.alter_column("releases", "status",
               existing_type=postgresql.ENUM("prerelease", "bugfix", "security", "eol", name="releasestatus"),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("releases", "status",
               existing_type=postgresql.ENUM("prerelease", "bugfix", "security", "eol", name="releasestatus"),
               server_default=sa.text("'bugfix'::releasestatus"),
               existing_nullable=False)
    op.drop_index(op.f("ix_blog_entries_is_featured"), table_name="blog_entries")
    op.drop_column("blog_entries", "is_featured")
    # ### end Alembic commands ###
